### ISSUE TITLE
TypeError: (0 , import_vite_plugin_live_reload.default) is not a function

### ISSUE THREAD

**Issue by n-kort** [arnoson/vite-plugin-kirby#1]
Can't run the `vite` command, unless I use `{ watch: false }` in the config.

`vite` version 3.1.4, this plugin version 0.1.0

**Comment by arnoson** [comment]
Seems to be an cjs issue, can you try setting your project to `"type": "module"` in the package.json?

**Comment by n-kort** [comment]
indeed it was, thanks for the pointer 🙏

**Comment by arnoson** [comment]
Great that it works! I'll leave this issue open untill I figured out why the cjs version is broken
