### ISSUE TITLE
Configurable .dev file path

### ISSUE THREAD

**Issue by holmey** [arnoson/vite-plugin-kirby#2]
When using this plugin outside of the root directory (e.g. when moving the frontend setup to a separate folder) the .dev file is not available in the root folder when starting the server. When this path would be configurable it could solve this issue.

https://github.com/arnoson/vite-plugin-kirby/blob/975e28cfc24c0e41f6b303f58f1d5458ff6e2890/src/index.ts#L18

**Comment by arnoson** [comment]
Good point! I will look into this. Would have to an option for both this plugin and the kirby plugin
To be consistent with the way we handle the watch paths the vite plugin option should be relative to vite's root

**Comment by arnoson** [comment]
I added this in [v0.2.0](https://github.com/arnoson/vite-plugin-kirby/releases/tag/v0.2.0)
The `devDir` is now relative to the `process.cwd()`. I also realized that it won't make sense to add an option to the kirby plugin.
